language: php

php:
  - 7.1.3

services:
  - postgresql

before_script:
  - mv .env.testing .env
  - psql -c 'create database sgecti;' -U postgres
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan config:cache
  - php artisan migrate --seed
