language: php
php:
  - 7.1.3

services:
  - postgresql

before_script:
  - psql -c 'create database sgecti;' -U postgres
  - composer install
  - php artisan key:generate
  - php artisan config:cache
  - php artisan migrate
